baseurl = "http://blog.the-captains-shack.com/"
languageCode = "en-us"
title = "The Captain's Shack"
theme = "casper"



contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
builddrafts = false
canonifyurls = true

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  description = "The perfect place for random experiments and explorations"
  author = "Jean-Marc MEESSEN"
  authorlocation = "Brussels, Belgium"
  authorwebsite = "https://the-captains-shack.com"
  cover = "images/cabin2.jpg"
  githubName = "jmMeessen"
  twitterName = "jm_meessen"
  hideHUGOSupport = false
  logo = "images/jmm_avatar.jpeg"

[[menu.main]]
  name = "My Blog"
  weight = -120
  identifier = "blog"
  url = "/"

[[menu.main]]
  name = "About this blog"
  weight = -110
  identifier = "about"
  url = "/about"

[[menu.main]]
  name = "About me"
  weight = -100
  identifier = "about_me"
  url = "/about_me"
