#docker run  hugo server --baseURL="http://192.168.99.100/" --bind=0.0.0.0

hugo-preview:
   build: hugo-dockerfile/
   ports:
      - "1313:1313"
   volumes:
      - ./site:/usr/share/blog/
   command: hugo server --watch --baseURL="http://192.168.99.100/" --bind=0.0.0.0

hugo-generate:
   build: hugo-dockerfile/
